"""v2 dispatcher — adapter interface, mock adapter, dispatch result tracking."""

import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional


@dataclass
class DispatchResult:
    success: bool
    error: Optional[str] = None
    output: Optional[str] = None
    duration_seconds: float = 0.0
    invocation_id: Optional[str] = None
    is_async: bool = False




# ---------------------------------------------------------------------------
# Abstract adapter interface
# ---------------------------------------------------------------------------

class Adapter:
    """Base adapter. Subclass for each real agent."""

    agent_id: str = "unknown"

    def invoke(
        self,
        role: str,
        seat: str,
        target_path: str,
        instruction: str,
        expected_output: str,
        timeout: int = 600,
    ) -> DispatchResult:
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Mock adapter
# ---------------------------------------------------------------------------

class MockAdapter(Adapter):
    """Mock adapter that simulates agent work by writing expected output files.

    For each dispatch, it reads the instruction, waits briefly, then
    writes a plausible-looking mock artifact to the expected output path.
    """

    agent_id = "mock"

    def __init__(self, delay_seconds: float = 0.1, fail_on: Optional[set[str]] = None):
        self.delay_seconds = delay_seconds
        self.fail_on = fail_on or set()

    def invoke(
        self,
        role: str,
        seat: str,
        target_path: str,
        instruction: str,
        expected_output: str,
        timeout: int = 600,
    ) -> DispatchResult:
        start = time.monotonic()

        if seat in self.fail_on or role in self.fail_on:
            return DispatchResult(success=False, error=f"Mock failure triggered for {seat}")

        time.sleep(self.delay_seconds)

        wf_dir = Path(expected_output).parent
        wf_dir.mkdir(parents=True, exist_ok=True)

        content = self._mock_content(role, seat, target_path, instruction)
        tmp = Path(expected_output + ".tmp")
        tmp.write_text(content, encoding="utf-8")
        tmp.rename(expected_output)

        duration = time.monotonic() - start
        return DispatchResult(success=True, output=content[:200], duration_seconds=duration)

    def _mock_content(self, role: str, seat: str, target_path: str, instruction: str) -> str:
        lines = [
            f"# Mock {role.upper()} Output: {seat}",
            "",
            f"**Generated by**: MockAdapter",
            f"**Target**: {target_path}",
            "",
        ]

        if role == "chair" and "clarify" in instruction.lower():
            lines += [
                "## Clarification",
                "The request is clear enough to proceed.",
                "",
                "## Goal",
                "Implement the requested changes.",
                "",
                "## Constraints",
                "- Follow existing code patterns",
                "- All tests must pass",
                "",
                "## Non-Goals",
                "- No unrelated refactoring",
                "",
                "## Planner Questions",
                "1. Which files need modification?",
                "2. What is the implementation order?",
                "3. What are the risks?",
                "",
                "## Final Plan Requirements",
                "The final plan must include a file-level change list, execution order, and verification steps.",
            ]

        elif role == "planner" and "comment" not in instruction.lower():
            lines += [
                "## Understanding",
                f"As {seat}, I've reviewed the target project and the chair's brief.",
                "",
                "## Proposed Approach",
                "1. Analyze current implementation",
                "2. Make targeted changes",
                "3. Run tests",
                "4. Document changes",
                "",
                "## Expected Scope",
                "**Add**: New implementation files",
                "**Modify**: Core logic files",
                "**Delete**: Deprecated code",
                "",
                "## Implementation Order",
                "1. Prepare test environment",
                "2. Implement core changes",
                "3. Update tests",
                "4. Verify",
                "",
                "## Risks",
                "- Backward compatibility",
                "- Test coverage gaps",
                "",
                "## Verification",
                "- Run full test suite",
                "- Manual review of changes",
                "",
                "## For Chair Decision",
                "- Confirmation on scope boundaries",
            ]

        elif role == "planner" and "comment" in instruction.lower():
            target = seat.split("_on_")[-1] if "_on_" in seat else "unknown"
            lines += [
                f"## Review of {target}'s proposal",
                "",
                "## What I Agree With",
                "- The overall approach is sound",
                "- The implementation order is logical",
                "",
                "## What's Missing",
                "- Error handling details",
                "- Migration strategy for existing data",
                "",
                "## Concerns",
                "- Risk #2 may be understated",
                "",
                "## Suggestions for Final Plan",
                "1. Include rollback procedures",
                "2. Add integration test coverage",
                "3. Specify data migration steps",
            ]

        elif role == "chair" and "synthesis" in instruction.lower():
            lines += [
                "# Final Plan",
                "",
                "## 1. Goal",
                "Implement the requested changes per user specification.",
                "",
                "## 2. Keep",
                "- Existing interfaces",
                "- Test structure",
                "",
                "## 3. Delete",
                "- Deprecated code paths",
                "",
                "## 4. Add/Modify",
                "See file-level change list below.",
                "",
                "## 5. File-Level Change List",
                "- `src/core.py` — modify main logic",
                "- `tests/test_core.py` — add new test cases",
                "",
                "## 6. Execution Order",
                "1. Branch from main",
                "2. Implement changes",
                "3. Run tests",
                "4. Submit for review",
                "",
                "## 7. Migration",
                "No data migration needed.",
                "",
                "## 8. Safety",
                "- Work on feature branch",
                "- Do not commit without review approval",
                "",
                "## 9. Verification",
                "Run the full test suite.",
                "",
                "## 10. Rollback",
                "Revert feature branch.",
                "",
                "## 11. Non-Goals",
                "- Unrelated refactoring",
            ]

        elif role == "executor" and "commit" not in instruction.lower():
            lines += [
                "# Execution Walkthrough",
                "",
                "## Changes Made",
                "- Updated core logic in `src/core.py`",
                "- Added tests in `tests/test_core.py`",
                "",
                "## Differences from Plan",
                "- Minor order adjustment for efficiency",
                "",
                "## Deletions",
                "- Removed deprecated helper function",
                "",
                "## Tests",
                "All tests pass.",
                "",
                "## Unresolved Issues",
                "None.",
                "",
                "## Branch Status",
                "- Branch: feature/implementation",
                "- Ready for review",
            ]

        elif role == "reviewer":
            lines += [
                "# Review",
                "",
                "DECISION: APPROVE",
                "",
                "## Summary",
                "The implementation follows the plan correctly.",
                "All tests pass. Code quality is acceptable.",
                "",
                "## No Issues Found",
            ]

        elif role == "executor" and "commit" in instruction.lower():
            lines += [
                "# Commit Record",
                "",
                "**Branch**: feature/implementation",
                "**Commit SHA**: abc123def456",
                "**Message**: Implement changes per final_plan",
                "",
                "## Test Results",
                "All tests pass.",
                "",
                "## Change Summary",
                "- Updated core logic",
                "- Added tests",
                "- Removed deprecated code",
            ]

        elif role == "chair" and "final" in instruction.lower():
            lines += [
                "# Completion Report",
                "",
                "**COMPLETED**",
                "",
                "## Summary",
                "All phases completed successfully.",
                "Tests pass. Code is clean.",
                "",
                "## Recommendations",
                "- Consider follow-up optimization in a future workflow",
            ]

        else:
            lines += [
                f"# {role.upper()} Output",
                "",
                "Task completed successfully.",
            ]

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Antigravity adapter helper & class
# ---------------------------------------------------------------------------

def discover_antigravity_credentials() -> dict[str, Optional[str]]:
    import os
    import re
    import subprocess
    import json

    address = os.environ.get("ANTIGRAVITY_LS_ADDRESS")
    csrf_token = os.environ.get("ANTIGRAVITY_CSRF_TOKEN")
    project_id = os.environ.get("ANTIGRAVITY_PROJECT_ID")

    # If already fully configured in environment, return it
    if address and csrf_token and project_id:
        return {
            "address": address,
            "csrf_token": csrf_token,
            "project_id": project_id
        }

    # Discover CSRF token from running language_server process
    discovered_csrf = None
    discovered_ports = []
    try:
        ps_output = subprocess.check_output(["ps", "aux"], text=True)
        ls_pids = []
        for line in ps_output.splitlines():
            if "language_server" in line and "--csrf_token" in line:
                parts = line.split()
                if len(parts) >= 2:
                    pid = parts[1]
                    ls_pids.append(pid)
                match = re.search(r"--csrf_token\s+([a-zA-Z0-9\-]+)", line)
                if match:
                    discovered_csrf = match.group(1)

        # For found PIDs, run lsof to get listening ports
        for pid in ls_pids:
            try:
                lsof_output = subprocess.check_output(["lsof", "-a", "-i", "-P", "-n", "-p", pid], text=True)
                for line in lsof_output.splitlines():
                    if "LISTEN" in line:
                        match = re.search(r"127\.0\.0\.1:(\d+)", line)
                        if match:
                            discovered_ports.append(int(match.group(1)))
            except Exception:
                pass
    except Exception:
        pass

    # Discover Project ID from app_storage.json
    discovered_project_id = None
    app_storage_path = os.path.expanduser("~/Library/Application Support/Antigravity/app_storage.json")
    if os.path.isfile(app_storage_path):
        try:
            with open(app_storage_path, "r", encoding="utf-8") as f:
                storage = json.load(f)
                discovered_project_id = storage.get("lastCreatedProjectId")
        except Exception:
            pass

    # Sort ports to prioritize higher port
    discovered_ports.sort(reverse=True)

    final_address = address
    if not final_address and discovered_ports:
        agentapi_path = os.path.expanduser("~/.gemini/antigravity/bin/agentapi")
        if os.path.isfile(agentapi_path):
            for p in discovered_ports:
                test_addr = f"localhost:{p}"
                test_env = os.environ.copy()
                test_env["ANTIGRAVITY_LS_ADDRESS"] = test_addr
                test_env["ANTIGRAVITY_CSRF_TOKEN"] = csrf_token or discovered_csrf or ""
                test_env["ANTIGRAVITY_PROJECT_ID"] = project_id or discovered_project_id or ""
                try:
                    res = subprocess.run(
                        [agentapi_path, "get-conversation-metadata", "00000000-0000-0000-0000-000000000000"],
                        env=test_env,
                        capture_output=True,
                        text=True,
                        timeout=5
                    )
                    try:
                        out_json = json.loads(res.stdout)
                        err_msg = out_json.get("error", "")
                        if "trajectory not found" in err_msg or ("rpc error" in err_msg and "Unavailable" not in err_msg and "connection error" not in err_msg):
                            final_address = test_addr
                            break
                    except Exception:
                        pass
                except Exception:
                    pass

    return {
        "address": final_address,
        "csrf_token": csrf_token or discovered_csrf,
        "project_id": project_id or discovered_project_id
    }


class AntigravityAdapter(Adapter):
    """Adapter for triggering the real Antigravity agent via agentapi."""

    agent_id = "antigravity"

    def invoke(
        self,
        role: str,
        seat: str,
        target_path: str,
        instruction: str,
        expected_output: str,
        timeout: int = 600,
    ) -> DispatchResult:
        import json
        import os
        import subprocess
        start_time = time.monotonic()
        expected_path = Path(expected_output)

        # If the artifact is already completed, return immediately
        if expected_path.is_file() and expected_path.stat().st_size > 0:
            tmp_path = expected_path.with_suffix(expected_path.suffix + ".tmp")
            if not tmp_path.is_file():
                # Clean up invocation file if exists
                invocation_file = expected_path.with_suffix(expected_path.suffix + ".invocation")
                if invocation_file.is_file():
                    try:
                        invocation_file.unlink()
                    except Exception:
                        pass
                return DispatchResult(
                    success=True,
                    output="Artifact already exists",
                    duration_seconds=0.0,
                    invocation_id="manual",
                    is_async=False
                )

        # Resolve the workflow directory by searching upwards for manifest.json
        wf_dir = expected_path.parent
        while wf_dir != wf_dir.parent:
            if (wf_dir / "manifest.json").is_file():
                break
            wf_dir = wf_dir.parent

        instruction_file_path = wf_dir / "instructions" / f"{seat}.md"

        # We store the invocation conversation ID in expected_output + ".invocation"
        invocation_file = expected_path.with_suffix(expected_path.suffix + ".invocation")
        conversation_id = None
        is_manual = False

        if invocation_file.is_file():
            try:
                state = json.loads(invocation_file.read_text(encoding="utf-8"))
                conversation_id = state.get("conversation_id")
                is_manual = state.get("manual_handoff", False)
                print(f"[antigravity] Found existing conversation ID: {conversation_id} (manual={is_manual}) from {invocation_file.name}")
            except Exception as e:
                print(f"[antigravity] Error reading invocation file: {e}")

        # Resolve the agentapi binary path.
        agentapi_path = os.path.expanduser("~/.gemini/antigravity/bin/agentapi")

        if not conversation_id and not is_manual:
            if not os.path.isfile(agentapi_path):
                print(f"[antigravity] agentapi binary not found at {agentapi_path}. Falling back to MANUAL HANDOFF.")
                is_manual = True
            else:
                credentials = discover_antigravity_credentials()

                if not credentials.get("address") or not credentials.get("csrf_token"):
                    print("[antigravity] Could not auto-discover address or CSRF token. Falling back to MANUAL HANDOFF.")
                    is_manual = True
                else:
                    prompt = (
                        f"You are dispatched as {role} ({seat}) in a MAW v2 workflow.\n"
                        f"Please read the instructions in the following file:\n"
                        f"{instruction_file_path}\n\n"
                        f"And implement the task, then write your output to the expected path:\n"
                        f"{expected_output}\n\n"
                        f"Remember to write your output atomically (to a .tmp file first, then rename it).\n"
                        f"Do not modify any code in the target project unless you are the executor."
                    )

                    print(f"[antigravity] Triggering agentapi new-conversation...")
                    try:
                        env = {
                            "ANTIGRAVITY_LS_ADDRESS": credentials["address"] or "",
                            "ANTIGRAVITY_CSRF_TOKEN": credentials["csrf_token"] or "",
                            "ANTIGRAVITY_PROJECT_ID": credentials["project_id"] or "",
                        }
                        for k in ["PATH", "HOME", "USER", "SHELL", "TMPDIR"]:
                            if k in os.environ:
                                env[k] = os.environ[k]

                        result = subprocess.run(
                            [agentapi_path, "new-conversation", prompt],
                            env=env,
                            capture_output=True,
                            text=True,
                            timeout=30,
                        )

                        if result.returncode != 0:
                            print(f"[antigravity] agentapi failed: {result.stderr or result.stdout}. Falling back to MANUAL HANDOFF.")
                            is_manual = True
                        else:
                            resp = json.loads(result.stdout)
                            conversation_id = resp["response"]["newConversation"]["conversationId"]
                            print(f"[antigravity] Started new conversation: {conversation_id}")

                            # Persist the conversation ID
                            invocation_file.parent.mkdir(parents=True, exist_ok=True)
                            invocation_file.write_text(json.dumps({
                                "conversation_id": conversation_id,
                                "role": role,
                                "seat": seat,
                                "expected_output": expected_output,
                                "started_at": time.time(),
                                "manual_handoff": False
                            }, indent=2), encoding="utf-8")
                    except Exception as e:
                        print(f"[antigravity] Exception when running agentapi: {e}. Falling back to MANUAL HANDOFF.")
                        is_manual = True

            if is_manual:
                invocation_file.parent.mkdir(parents=True, exist_ok=True)
                invocation_file.write_text(json.dumps({
                    "conversation_id": "manual",
                    "role": role,
                    "seat": seat,
                    "expected_output": expected_output,
                    "started_at": time.time(),
                    "manual_handoff": True
                }, indent=2), encoding="utf-8")

        if is_manual or conversation_id == "manual":
            print("=" * 80)
            print("[ANTIGRAVITY MANUAL HANDOFF REQUIRED]")
            print(f"Please open Antigravity and execute the instruction:")
            print(f"Instruction file: {instruction_file_path}")
            print(f"Expected output:   {expected_output}")
            print("=" * 80)

        # Return immediately in async mode
        duration = time.monotonic() - start_time
        return DispatchResult(
            success=True,
            output=f"Agent dispatched successfully. Mode: {'Manual' if is_manual else 'Antigravity'}",
            duration_seconds=duration,
            invocation_id=conversation_id or "manual",
            is_async=True
        )



# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

_registry: dict[str, Adapter] = {
    "mock": MockAdapter(),
    "antigravity": AntigravityAdapter(),
}


def register_adapter(agent_id: str, adapter: Adapter) -> None:
    _registry[agent_id] = adapter


def get_adapter(agent_id: str) -> Optional[Adapter]:
    return _registry.get(agent_id)


def list_adapters() -> list[str]:
    return sorted(_registry.keys())


# ---------------------------------------------------------------------------
# Dispatch function
# ---------------------------------------------------------------------------

def dispatch(
    item,
    wf_dir: Path,
    instruction: str,
    timeout: int = 600,
) -> DispatchResult:
    """Dispatch work to the appropriate adapter for the given agent."""
    adapter = get_adapter(item.agent)
    if adapter is None:
        return DispatchResult(success=False, error=f"No adapter for agent '{item.agent}'")

    from v2.schema import (
        proposal_path,
        comment_path,
        walkthrough_path,
        review_path,
        ARTIFACT_CHAIR_BRIEF,
        ARTIFACT_FINAL_PLAN,
        ARTIFACT_COMMIT,
        ARTIFACT_COMPLETION,
        ARTIFACT_QUESTIONS,
    )

    # Determine expected output path
    if item.role == "chair" and item.phase == "clarify":
        expected = str(wf_dir / ARTIFACT_CHAIR_BRIEF)
    elif item.role == "planner" and item.phase == "proposal":
        expected = str(wf_dir / proposal_path(item.seat))
    elif item.role == "planner" and item.phase == "comment":
        # Parse reviewer_target from the dispatch key: wf_id:comment:planner_a_on_planner_b:1
        key_parts = item.key.split(":")
        if len(key_parts) >= 3:
            seat_pair = key_parts[2]
            parts = seat_pair.split("_on_")
            if len(parts) == 2:
                expected = str(wf_dir / comment_path(parts[0], parts[1]))
            else:
                return DispatchResult(success=False, error=f"Invalid comment key: {item.key}")
        else:
            return DispatchResult(success=False, error=f"Invalid comment key: {item.key}")
    elif item.role == "chair" and item.phase == "synthesis":
        expected = str(wf_dir / ARTIFACT_FINAL_PLAN)
    elif item.role == "executor" and item.phase == "execution":
        expected = str(wf_dir / walkthrough_path(item.iteration))
    elif item.role == "reviewer" and item.phase == "review":
        expected = str(wf_dir / review_path(item.iteration))
    elif item.role == "executor" and item.phase == "commit":
        expected = str(wf_dir / ARTIFACT_COMMIT)
    elif item.role == "chair" and item.phase == "final_check":
        expected = str(wf_dir / ARTIFACT_COMPLETION)
    else:
        return DispatchResult(success=False, error=f"Unknown dispatch: role={item.role} phase={item.phase}")

    # Build target path from manifest for adapter
    manifest_path = wf_dir / "manifest.json"
    import json
    with open(manifest_path) as f:
        manifest = json.load(f)
    target_path = manifest.get("target_path", str(wf_dir))

    return adapter.invoke(
        role=item.role,
        seat=item.seat,
        target_path=target_path,
        instruction=instruction,
        expected_output=expected,
        timeout=timeout,
    )


def cancel_item(item) -> None:
    """Cancel an in-flight dispatch. Mock doesn't need cancellation."""
    pass
