"""v2 dispatcher — adapter interface, mock adapter, dispatch result tracking."""

import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional


@dataclass
class DispatchResult:
    success: bool
    error: Optional[str] = None
    output: Optional[str] = None
    duration_seconds: float = 0.0


# ---------------------------------------------------------------------------
# Abstract adapter interface
# ---------------------------------------------------------------------------

class Adapter:
    """Base adapter. Subclass for each real agent."""

    agent_id: str = "unknown"

    def invoke(
        self,
        role: str,
        seat: str,
        target_path: str,
        instruction: str,
        expected_output: str,
        timeout: int = 600,
    ) -> DispatchResult:
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Mock adapter
# ---------------------------------------------------------------------------

class MockAdapter(Adapter):
    """Mock adapter that simulates agent work by writing expected output files.

    For each dispatch, it reads the instruction, waits briefly, then
    writes a plausible-looking mock artifact to the expected output path.
    """

    agent_id = "mock"

    def __init__(self, delay_seconds: float = 0.1, fail_on: Optional[set[str]] = None):
        self.delay_seconds = delay_seconds
        self.fail_on = fail_on or set()

    def invoke(
        self,
        role: str,
        seat: str,
        target_path: str,
        instruction: str,
        expected_output: str,
        timeout: int = 600,
    ) -> DispatchResult:
        start = time.monotonic()

        if seat in self.fail_on or role in self.fail_on:
            return DispatchResult(success=False, error=f"Mock failure triggered for {seat}")

        time.sleep(self.delay_seconds)

        wf_dir = Path(expected_output).parent
        wf_dir.mkdir(parents=True, exist_ok=True)

        content = self._mock_content(role, seat, target_path, instruction)
        tmp = Path(expected_output + ".tmp")
        tmp.write_text(content, encoding="utf-8")
        tmp.rename(expected_output)

        duration = time.monotonic() - start
        return DispatchResult(success=True, output=content[:200], duration_seconds=duration)

    def _mock_content(self, role: str, seat: str, target_path: str, instruction: str) -> str:
        lines = [
            f"# Mock {role.upper()} Output: {seat}",
            "",
            f"**Generated by**: MockAdapter",
            f"**Target**: {target_path}",
            "",
        ]

        if role == "chair" and "clarify" in instruction.lower():
            lines += [
                "## Clarification",
                "The request is clear enough to proceed.",
                "",
                "## Goal",
                "Implement the requested changes.",
                "",
                "## Constraints",
                "- Follow existing code patterns",
                "- All tests must pass",
                "",
                "## Non-Goals",
                "- No unrelated refactoring",
                "",
                "## Planner Questions",
                "1. Which files need modification?",
                "2. What is the implementation order?",
                "3. What are the risks?",
                "",
                "## Final Plan Requirements",
                "The final plan must include a file-level change list, execution order, and verification steps.",
            ]

        elif role == "planner" and "comment" not in instruction.lower():
            lines += [
                "## Understanding",
                f"As {seat}, I've reviewed the target project and the chair's brief.",
                "",
                "## Proposed Approach",
                "1. Analyze current implementation",
                "2. Make targeted changes",
                "3. Run tests",
                "4. Document changes",
                "",
                "## Expected Scope",
                "**Add**: New implementation files",
                "**Modify**: Core logic files",
                "**Delete**: Deprecated code",
                "",
                "## Implementation Order",
                "1. Prepare test environment",
                "2. Implement core changes",
                "3. Update tests",
                "4. Verify",
                "",
                "## Risks",
                "- Backward compatibility",
                "- Test coverage gaps",
                "",
                "## Verification",
                "- Run full test suite",
                "- Manual review of changes",
                "",
                "## For Chair Decision",
                "- Confirmation on scope boundaries",
            ]

        elif role == "planner" and "comment" in instruction.lower():
            target = seat.split("_on_")[-1] if "_on_" in seat else "unknown"
            lines += [
                f"## Review of {target}'s proposal",
                "",
                "## What I Agree With",
                "- The overall approach is sound",
                "- The implementation order is logical",
                "",
                "## What's Missing",
                "- Error handling details",
                "- Migration strategy for existing data",
                "",
                "## Concerns",
                "- Risk #2 may be understated",
                "",
                "## Suggestions for Final Plan",
                "1. Include rollback procedures",
                "2. Add integration test coverage",
                "3. Specify data migration steps",
            ]

        elif role == "chair" and "synthesis" in instruction.lower():
            lines += [
                "# Final Plan",
                "",
                "## 1. Goal",
                "Implement the requested changes per user specification.",
                "",
                "## 2. Keep",
                "- Existing interfaces",
                "- Test structure",
                "",
                "## 3. Delete",
                "- Deprecated code paths",
                "",
                "## 4. Add/Modify",
                "See file-level change list below.",
                "",
                "## 5. File-Level Change List",
                "- `src/core.py` — modify main logic",
                "- `tests/test_core.py` — add new test cases",
                "",
                "## 6. Execution Order",
                "1. Branch from main",
                "2. Implement changes",
                "3. Run tests",
                "4. Submit for review",
                "",
                "## 7. Migration",
                "No data migration needed.",
                "",
                "## 8. Safety",
                "- Work on feature branch",
                "- Do not commit without review approval",
                "",
                "## 9. Verification",
                "Run the full test suite.",
                "",
                "## 10. Rollback",
                "Revert feature branch.",
                "",
                "## 11. Non-Goals",
                "- Unrelated refactoring",
            ]

        elif role == "executor" and "commit" not in instruction.lower():
            lines += [
                "# Execution Walkthrough",
                "",
                "## Changes Made",
                "- Updated core logic in `src/core.py`",
                "- Added tests in `tests/test_core.py`",
                "",
                "## Differences from Plan",
                "- Minor order adjustment for efficiency",
                "",
                "## Deletions",
                "- Removed deprecated helper function",
                "",
                "## Tests",
                "All tests pass.",
                "",
                "## Unresolved Issues",
                "None.",
                "",
                "## Branch Status",
                "- Branch: feature/implementation",
                "- Ready for review",
            ]

        elif role == "reviewer":
            lines += [
                "# Review",
                "",
                "DECISION: APPROVE",
                "",
                "## Summary",
                "The implementation follows the plan correctly.",
                "All tests pass. Code quality is acceptable.",
                "",
                "## No Issues Found",
            ]

        elif role == "executor" and "commit" in instruction.lower():
            lines += [
                "# Commit Record",
                "",
                "**Branch**: feature/implementation",
                "**Commit SHA**: abc123def456",
                "**Message**: Implement changes per final_plan",
                "",
                "## Test Results",
                "All tests pass.",
                "",
                "## Change Summary",
                "- Updated core logic",
                "- Added tests",
                "- Removed deprecated code",
            ]

        elif role == "chair" and "final" in instruction.lower():
            lines += [
                "# Completion Report",
                "",
                "**COMPLETED**",
                "",
                "## Summary",
                "All phases completed successfully.",
                "Tests pass. Code is clean.",
                "",
                "## Recommendations",
                "- Consider follow-up optimization in a future workflow",
            ]

        else:
            lines += [
                f"# {role.upper()} Output",
                "",
                "Task completed successfully.",
            ]

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

_registry: dict[str, Adapter] = {
    "mock": MockAdapter(),
}


def register_adapter(agent_id: str, adapter: Adapter) -> None:
    _registry[agent_id] = adapter


def get_adapter(agent_id: str) -> Optional[Adapter]:
    return _registry.get(agent_id)


def list_adapters() -> list[str]:
    return sorted(_registry.keys())


# ---------------------------------------------------------------------------
# Dispatch function
# ---------------------------------------------------------------------------

def dispatch(
    item,
    wf_dir: Path,
    instruction: str,
    timeout: int = 600,
) -> DispatchResult:
    """Dispatch work to the appropriate adapter for the given agent."""
    adapter = get_adapter(item.agent)
    if adapter is None:
        return DispatchResult(success=False, error=f"No adapter for agent '{item.agent}'")

    from v2.schema import (
        proposal_path,
        comment_path,
        walkthrough_path,
        review_path,
        ARTIFACT_CHAIR_BRIEF,
        ARTIFACT_FINAL_PLAN,
        ARTIFACT_COMMIT,
        ARTIFACT_COMPLETION,
        ARTIFACT_QUESTIONS,
    )

    # Determine expected output path
    if item.role == "chair" and item.phase == "clarify":
        expected = str(wf_dir / ARTIFACT_CHAIR_BRIEF)
    elif item.role == "planner" and item.phase == "proposal":
        expected = str(wf_dir / proposal_path(item.seat))
    elif item.role == "planner" and item.phase == "comment":
        # Parse reviewer_target from the dispatch key: wf_id:comment:planner_a_on_planner_b:1
        key_parts = item.key.split(":")
        if len(key_parts) >= 3:
            seat_pair = key_parts[2]
            parts = seat_pair.split("_on_")
            if len(parts) == 2:
                expected = str(wf_dir / comment_path(parts[0], parts[1]))
            else:
                return DispatchResult(success=False, error=f"Invalid comment key: {item.key}")
        else:
            return DispatchResult(success=False, error=f"Invalid comment key: {item.key}")
    elif item.role == "chair" and item.phase == "synthesis":
        expected = str(wf_dir / ARTIFACT_FINAL_PLAN)
    elif item.role == "executor" and item.phase == "execution":
        expected = str(wf_dir / walkthrough_path(item.iteration))
    elif item.role == "reviewer" and item.phase == "review":
        expected = str(wf_dir / review_path(item.iteration))
    elif item.role == "executor" and item.phase == "commit":
        expected = str(wf_dir / ARTIFACT_COMMIT)
    elif item.role == "chair" and item.phase == "final_check":
        expected = str(wf_dir / ARTIFACT_COMPLETION)
    else:
        return DispatchResult(success=False, error=f"Unknown dispatch: role={item.role} phase={item.phase}")

    # Build target path from manifest for adapter
    manifest_path = wf_dir / "manifest.json"
    import json
    with open(manifest_path) as f:
        manifest = json.load(f)
    target_path = manifest.get("target_path", str(wf_dir))

    return adapter.invoke(
        role=item.role,
        seat=item.seat,
        target_path=target_path,
        instruction=instruction,
        expected_output=expected,
        timeout=timeout,
    )


def cancel_item(item) -> None:
    """Cancel an in-flight dispatch. Mock doesn't need cancellation."""
    pass
